### ISSUE TITLE
simple block div

### ISSUE THREAD

**Issue by ocean123** [giansi/gravstrap#12]
Hi,

How can I make a simple div with some text and a class.

`[g-div name=myBlock attributes="class:myDivBlock"]  
Lorem ipsum dolor sit amet, consectetur adipiscing elit.  
Phasellus malesuada ante sit amet nisi rhoncus luctus. Vivamus vel mi vel arcu euismod lobortis.  
[/g-div]
`

I can't find it on your website or wiki

Best regards
Ocean

**Comment by giansi** [comment]
Hi,
in order to make a simple div, you must add a new shortcode. Don't know if the best choice is adding a gravstrap shortcode for this, maybe a generic one would be better

[div name=myBlock attributes="class:myDivBlock"] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada ante sit amet nisi rhoncus luctus. Vivamus vel mi vel arcu euismod lobortis. [/div]

If you want to make it generic, you can follow these instructions: https://github.com/getgrav/grav-plugin-shortcode-core#developing-shortcode-plugins, if you want to go with a gravstrap shortcode, you can look at https://github.com/giansi/gravstrap/blob/master/shortcodes/Bootstrap/PanelShortcode.php and try to implement the new shortcode starting from this one.
