### ISSUE TITLE
How do i modify the CSS/Sass from the Theme

### ISSUE THREAD

**Issue by SomeGuyFromNowhere** [giansi/gravstrap#21]
Hello Giansi,

Sorry for this Noob Question. Which files do i need modify if want to change the Look of Gravstrap?

Modifying the Sass and CSS files led me nowhere, also when i was compiling the Files with Koala, as Sass/Compass GUI, nothing was happening. 

Can you give me a little heads up?
Thanks in advance

**Comment by giansi** [comment]
Hi,
the best way to achieve that task is to override the styles you want to change in a custom theme, because, if you change something directly into the gravstrap theme or plugin you risk to loose your changes when a new release is deployed.

Anyway for the plugin the sass files are save here: gravstrap/user/plugins/gravstrap/sass/lib and here for the theme: gravstrap/user/themes/gravstrap-theme/sass/lib.

I use compass http://compass-style.org/reference/compass/css3/ to compile them, so I can't help with Koala, because I don't know it

**Comment by SomeGuyFromNowhere** [comment]
Thank You!
